{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fato_bolsa_familia\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "75ebdfa3-75e9-96fa-fe8c-85fdc0ee7394",
        "fromColumn": "UF",
        "fromTable": "fato_bolsa_familia",
        "toColumn": "UF",
        "toTable": "dim_regioes"
      },
      {
        "name": "494a6785-2828-d127-2c36-cee1b6747663",
        "fromColumn": "Regiao",
        "fromTable": "dim_regioes",
        "toColumn": "regiao_permitida",
        "toTable": "dim_usuarios_rls"
      }
    ],
    "roles": [
      {
        "name": "Admin",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b723cfabf48749d89dba524a796125f5"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "Gestor_Norte",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "38e05eecec05463aa66138e457cec525"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Norte\""
          }
        ]
      },
      {
        "name": "Gestor_Nordeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "84796f10d50244248c2ed9c4f6fe9cc0"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Nordeste\""
          }
        ]
      },
      {
        "name": "Gestor_CentroOeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "948b59f149c84e9ebb98745b05a5b89d"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Centro Oeste\""
          }
        ]
      },
      {
        "name": "Gestor_Sudeste",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a4ba7d5fb7cd41f4b8af3c791f6ea0e8"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Sudeste\""
          }
        ]
      },
      {
        "name": "Gestor_Sul",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "94d47f98a2814b3e8f587e8ff41fa6e3"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_regioes",
            "filterExpression": "[Regiao] == \"Sul \""
          }
        ]
      },
      {
        "name": "Gestor_Regional_Dinamico",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ae409fd19f3449809236c92daa522046"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "dim_usuarios_rls",
            "filterExpression": "[email_usuario] = USERPRINCIPALNAME()"
          },
          {
            "name": "dim_regioes"
          }
        ]
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "fato_bolsa_familia",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5535c43d-549d-4030-a872-5c88e9846b20",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "CÓDIGO MUNICÍPIO SIAFI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57a45031-fdfc-49c6-8ecb-cab8cdfc5047",
            "sourceColumn": "CÓDIGO MUNICÍPIO SIAFI",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME MUNICÍPIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f3fdac3-b960-479e-b750-c76290d841f5",
            "sourceColumn": "NOME MUNICÍPIO",
            "summarizeBy": "none"
          },
          {
            "name": "CPF FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "682b6bde-90ba-46b7-9dda-4a2cb4b774a2",
            "sourceColumn": "CPF FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "NIS FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66854632-71d2-46dc-a3a2-2a59e09c3837",
            "sourceColumn": "NIS FAVORECIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "NOME FAVORECIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd94c85a-0526-4318-81b3-c1b03d5dcc5a",
            "sourceColumn": "NOME FAVORECIDO",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR PARCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca65e0d1-3a90-4b15-927b-584da42442d5",
            "sourceColumn": "VALOR PARCELA",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ca09247-f7d9-4e01-8e9b-14c5d1fca32a",
            "sourceColumn": "ANO",
            "summarizeBy": "none"
          },
          {
            "name": "MÊS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "506cc89b-bda5-4296-953b-23cbe2663921",
            "sourceColumn": "MÊS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7965e709-2ea7-4335-9848-dd9cdb4d4dbe",
        "partitions": [
          {
            "name": "fato_bolsa_familia",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\lanna.soares\\Downloads\\amostra_bolsa.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"MÊS COMPETÊNCIA\", Int64.Type}, {\"UF\", type text}, {\"CÓDIGO MUNICÍPIO SIAFI\", Int64.Type}, {\"NOME MUNICÍPIO\", type text}, {\"CPF FAVORECIDO\", type text}, {\"NIS FAVORECIDO\", Int64.Type}, {\"NOME FAVORECIDO\", type text}, {\"VALOR PARCELA\", Int64.Type}}),",
                "    #\"Texto Inserido Antes do Delimitador\" = Table.AddColumn(#\"Tipo Alterado\", \"Texto Antes do Delimitador\", each Text.BeforeDelimiter(Text.From([MÊS COMPETÊNCIA], \"pt-BR\"), \"0\", 1), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Texto Inserido Antes do Delimitador\",{{\"Texto Antes do Delimitador\", \"ANO\"}}),",
                "    #\"Texto Inserido Após o Delimitador\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Texto Após o Delimitador\", each Text.AfterDelimiter(Text.From([MÊS COMPETÊNCIA], \"pt-BR\"), \"6\"), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Texto Inserido Após o Delimitador\",{{\"Texto Após o Delimitador\", \"MÊS\"}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Colunas Renomeadas1\",{\"MÊS COMPETÊNCIA\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_4e42c0c4-ac8b-4b28-ac57-881845e69d70",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0404b1a6-d63b-47b6-8b06-c997050e7d95",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ba7d871b-0920-440a-8caf-c38c4de6af86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "248d2c6a-0942-4e28-8df2-17fbe70d5da5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b362639e-c82f-46c7-b93b-9a91a29317ab",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f220166-f01a-43a2-932f-1f4454cdccbe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3b009349-0550-458e-91cf-1c9eea53c671",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9e69ad81-15c6-4289-a7da-76cf6035456b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "7a2d42f5-1d9a-4b99-be7e-b8729d47e900",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "f5e0f2f8-5692-42c5-a0a9-ef31c56021c3",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "f35ac5a4-aa8e-4af2-a9f6-274194b8569f",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "01c8208c-c660-4e52-a2fa-1b4e690b882f",
                "ordinal": 3
              }
            ],
            "lineageTag": "4c867924-6c74-4ce2-837f-6f53beba0150"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a2367194-2a66-4916-9382-4f453971b713",
        "partitions": [
          {
            "name": "DateTableTemplate_4e42c0c4-ac8b-4b28-ac57-881845e69d70",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_usuarios_rls",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bb1f2fb585a74e108f9e2abf90358ad6"
          }
        ],
        "columns": [
          {
            "name": "email_usuario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f3f618f5-3440-4101-b327-9102f68ce641",
            "sourceColumn": "[email_usuario]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "regiao_permitida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "59ea1eb6-2b25-41e0-b002-9383a30cafda",
            "sourceColumn": "[regiao_permitida]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "eebe675d-be3b-496f-bd80-6128696f11e1",
        "partitions": [
          {
            "name": "dim_usuarios_rls",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"email_usuario\", STRING,",
                "    \"regiao_permitida\", STRING,",
                "    {",
                "        {\"gestor.norte@ministerio.br\", \"Norte\"},",
                "        {\"gestor.nordeste@ministerio.br\", \"Nordeste\"},",
                "        {\"gestor.centroeste@ministerio.br\", \"Centro-Oeste\"},",
                "        {\"gestor.sudeste@ministerio.br\", \"Sudeste\"},",
                "        {\"gestor.sul@ministerio.br\", \"Sul\"}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_regioes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a3abf1a5bd554cc5971f3d33573b93fa"
          }
        ],
        "columns": [
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dcc841af-a299-4760-b72e-40ae53c784f0",
            "sourceColumn": "[Regiao]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "947388de-a68f-4133-917c-fd7b1d694a42",
            "sourceColumn": "[UF]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "77bd2eb4-11f9-4298-8fe4-e6ce013bbf56",
        "partitions": [
          {
            "name": "dim_regioes",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "DATATABLE(",
                "    \"Regiao\", STRING,",
                "    \"UF\", STRING,",
                "    {",
                "        {\"Norte\", \"AC\"},",
                "        {\"Norte\", \"AM\"},",
                "        {\"Norte\", \"AP\"},",
                "        {\"Norte\", \"PA\"},",
                "        {\"Norte\", \"RO\"},",
                "        {\"Norte\", \"RR\"},",
                "        {\"Norte\", \"TO\"},",
                "        {\"Nordeste\", \"AL\"},",
                "        {\"Nordeste\", \"BA\"},",
                "        {\"Nordeste\", \"CE\"},",
                "        {\"Nordeste\", \"MA\"},",
                "        {\"Nordeste\", \"PB\"},",
                "        {\"Nordeste\", \"PE\"},",
                "        {\"Nordeste\", \"PI\"},",
                "        {\"Nordeste\", \"RN\"},",
                "        {\"Nordeste\", \"SE\"},",
                "        {\"Centro-Oeste\", \"DF\"},",
                "        {\"Centro-Oeste\", \"GO\"},",
                "        {\"Centro-Oeste\", \"MS\"},",
                "        {\"Centro-Oeste\", \"MT\"},",
                "        {\"Sudeste\", \"ES\"},",
                "        {\"Sudeste\", \"MG\"},",
                "        {\"Sudeste\", \"RJ\"},",
                "        {\"Sudeste\", \"SP\"},",
                "        {\"Sul\", \"PR\"},",
                "        {\"Sul\", \"RS\"},",
                "        {\"Sul\", \"SC\"}",
                "    }",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}